name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@7b392529550f2963dc0022428e873ddb17cdedd4
    with:
      python-version: "3.12"
      working-directory: "."
      unison-common-ref: "52d4b3dfdd71f15d8169b70e1dec05dc8a0c6f30"
