name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  python-security:
    uses: project-unisonOS/.github/.github/workflows/reusable-python-security.yml@7b392529550f2963dc0022428e873ddb17cdedd4
    with:
      python-version: "3.12"
      working-directory: "."
      unison-common-ref: "d3ff64ab70865e63bd7e40c9618a5c89c1079df7"
